### ISSUE TITLE
Building for arm64 UWP

### ISSUE THREAD

**Issue by FreakTheMighty** [virtualplaynl/couchbase-lite-unity#2]
I'd like to evaluate couchdb in Unity. Any chance you could provide some documentation about what changes were required and how to perform a build?

It would be REALLY cool to get this repo updated and potentially set it up to use github actions to codify the build process and make it easier to keep up-to-date with couchdb.

**Comment by sabvdf** [comment]
It's a bit late reply and not even a helpful one at that: We ended up moving away from couchdb, and I honestly don't remember, sorry!

**Comment by FreakTheMighty** [comment]
Thanks for the update! I'll close this out
